name: mi_card
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Playfair
      fonts:
        - asset: fonts/PlayfairDisplay-VariableFont_wght.ttf
    - family: SourceSans
      fonts:
        - asset: fonts/SourceSans3-VariableFont_wght.ttf
